Add learning rate schedule example
DLR-RM/stable-baselines3 pull request #248
Opened 2020-12-01 16:20 UTC by araffin

## Description

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)

closes #246 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [ ] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)
- [ ] I have checked that the documentation builds using `make doc` (**required**)

Note: You can run most of the checks using `make commit-checks`.

Note: we are using a maximum length of 127 characters per line

2020-12-01 17:07 UTC, AdamGleave requested changes
Thanks for adding the example -- couple of changes suggested to improve clarity, but mostly LGTM

2020-12-01 17:07 UTC, AdamGleave commented on docs/guide/examples.rst
> +All algorithms allow to pass a learning rate schedule that takes as input the current progress remaining (from 1 to 0).
```suggestion
All algorithms allow you to pass a learning rate schedule that takes as input the current progress remaining (from 1 to 0).
```
Or "allow one".

2020-12-01 17:07 UTC, AdamGleave commented on docs/guide/examples.rst
> +  # On the second call, by default, the learning rate schedule resets
I find it a bit confusing that we have "by default" here and then manually specify `reset_num_timesteps` to True. I'd suggest either dropping the keyword argument, or clarifying the comment: "By default, `reset_num_timesteps` is True, in which case the learning rate schedule resets."

2020-12-02 12:20 UTC, AdamGleave approved these changes
LGTM, thanks for the changes

2020-12-02 13:54 UTC, araffin commented
>LGTM, thanks for the changes

Thanks for the review =) (next time you can merge it once you agree with the changes ;) )

2020-12-02 13:54 UTC, merged